name: Publish blog
on:
  workflow_dispatch:

jobs:
  publish:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
      - name: Build site
        run: make deploy-build